### PR TITLE
Master

### PR DESCRIPTION
**Pull request by dredknight**
build-exe.rb
=====================
new: GUI size unified, menus are aligned in center, look and feel is the same for the whole app instead of different on each step
new: added '*' mark to show required fields
new: Wizzard will not conitnue if required fields are empty
new: start menu folder name - not required field in case the user wants appname and startname to differ. If empty appname is chosen as default value.
new: YAML output prints only non zero values. The same is valid for the summary page presentation.
fixed: build-exe.rb script: "Load yaml" option did not load gems.

merger-exe.rb
=====================
fixed: Gems were not included in the app at all even if chosen by the user
 //it seems merger-exe module was patched on a several occasions to adjust to new Shoes behavior where at the end it has stopped working
 //The new method works the following way merger-exe copy all gems and specs to the app and delete all but the one included. It works like a charm and saves a bunch of space!
fixed: Various tooltips typos; made them more descriptive
fixed: No default app icon was picked if the user do not specify custom one. The path was wrong, furthermore this field is in required fields so it cannot be skipped.

NSIS.nsi
=====================
added: start menu name variable (this was done a long time ago and it exists in the current exe-shoes but it was not documented)
fixed: NSIS script: app subname was not added to the instalation exe file

ytm.yaml
=====================
fixed: ytm.yaml example gems syntax (it included gems version which is not consided by the script so gems were disregarded)
fixed: Various yaml syntax inconsistences

DEPENDENCIES
=====================
the packager now includes portable versions of NSIS and Resource hacker so there is no need for the user to install anything. They are found in directory potable_apps

### CODE REVIEW

**Comment by dredknight** [comment]
@ccoupe @BackOrder this is a very bold update so I am not going to complain if you discard it.
Summing it all up it is a merge of fixed stuff + the user guide and tooltips you have created!

Please give it a few tests if you have an occasion to do so I am not in a hurry so we can postpone this for any time in the future.

Thanks!

**Comment by IanTrudel** [comment]
> the packager now includes portable versions of NSIS and Resource hacker so there is no need for the user to install anything. They are found in directory potable_apps

I am not sure how I feel about dependencies included. It is not necessarily a bad thing but it is rather large and traditionally we did not include any such thing with Shoes. What do you think about it @ccoupe ?

By the way, if you have time, it would be great to add a simple multi-page code to contributed tips. :)

**Comment by dredknight** [comment]
@BackOrder I will do that. Moreover I found out absolutely different way to make multiple pages which is even simpler!

Regarding the dependency thing I have 2 proposals (besides disregarding them completely):
- add option to switch between the embedded portable apps and the user installed one
- make it use user installed one but add an option to download a separate package with portable one (it will be an archive that will be downloaded on the go from the app itself, unarchived and deployed automatically - I have already done this for my second app. I will make a showcase sometime later :) ).

Also however this pull request goes we are closing this issue shoes/shoes3#302

**Review by ccoupe — COMMENTED** [review]
I'n not a fan of the portable_apps directory being part of the exe-shoes repo - can you add that dir to your .gitignore file? or exclude it from the pull request?  

I'm not a fan of having the nsis-2.46.5-Unicode-setup.exe in the repo either (my mistake, I know) but it's relatively small - 1.8MB. The  current distribution method for exe-shoes is to git clone or git download so having nsis.exe be part of that clone might be helpful for the downloader in which case the repo is missing the resourcehacker.exe  I'm not in favor of installing those on the user's system - they have to do that themselves. 

The changes to the Shoes code look reasonable to me but I can't merge and test without dragging in all that portables_apps code.

**Comment by dredknight** [comment]
Portable_apps folder is now ignored.
Forgot to mention there is one thing I have removed from the current master branch GUI, this is the HKEY value. It is still there but not available to the user to fill in. Merger-exe assigns value of _mwanilla.com_. 

I did it because I am not sure what this value is for and I could not see a reason why the user will need it.
This is easily fixable though.

**Pull request closed without merging**
